// Tab1
export const STARGATE_HOME = 'STARGATE_HOME'
export const STARGATE_DETAILS = 'STARGATE_DETAILS'

// Tab1
export const BATMAN_HOME = 'BATMAN_HOME'
export const BATMAN_DETAILS = 'BATMAN_DETAILS'

// Tab1
export const SPIDER_HOME = 'SPIDER_HOME'
export const SPIDER_DETAILS = 'SPIDER_DETAILS'

